# Generated by Django 3.0.8 on 2020-07-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=90, null=True)),
                ('last_name', models.CharField(max_length=90, null=True)),
                ('middle_name', models.CharField(max_length=90)),
                ('birth_date', models.DateField()),
                ('privilege_type', models.CharField(choices=[('Ветеран', 'Ветеран'), ('Чернобыль', 'Чернобыль'), ('Ребёнок-инвалид до 18 лет', 'Ребёнок-инвалид до 18 лет'), ('Инвалид I - II группы', 'Инвалид I - II группы'), ('Инвалид III группы', 'Инвалид III группы')], default=0, max_length=90)),
                ('medication', models.CharField(max_length=90)),
                ('date_of_recipe', models.DateField()),
                ('date_of_getting', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Льготники',
            },
        ),
    ]
