# Generated by Django 3.0.8 on 2020-07-20 10:10

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=90, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=90, null=True, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=90, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('privilege_type', models.CharField(choices=[('Ветеран', 'Ветеран'), ('Чернобыль', 'Чернобыль'), ('Ребёнок-инвалид до 18 лет', 'Ребёнок-инвалид до 18 лет'), ('Инвалид I - II группы', 'Инвалид I - II группы'), ('Инвалид III группы', 'Инвалид III группы')], default=0, max_length=90, verbose_name='Льгота')),
                ('medication', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=90), blank=True, null=True, size=6)),
                ('date_of_recipe', models.DateField(verbose_name='Дата выдачи рецепта')),
            ],
            options={
                'verbose_name_plural': 'Льготники',
            },
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=90, null=True, verbose_name='Показатель')),
                ('type_1', models.IntegerField(default=0, editable=False, verbose_name='Ветеран')),
                ('type_2', models.IntegerField(default=0, editable=False, verbose_name='Чернобыль')),
                ('type_3', models.IntegerField(default=0, editable=False, verbose_name='Ребёнок-инвалид до 18 лет')),
                ('type_4', models.IntegerField(default=0, editable=False, verbose_name='Инвалид I - II группы')),
                ('type_5', models.IntegerField(default=0, editable=False, verbose_name='Инвалид III группы')),
            ],
            options={
                'verbose_name_plural': 'Статистика',
            },
        ),
    ]
