# Generated by Django 3.0.8 on 2020-07-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_1', models.IntegerField(default=0, editable=False, verbose_name='Инвалид II группы')),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='date_of_getting',
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_recipe',
            field=models.DateField(verbose_name='Дата выдачи рецепта'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=90, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=90, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medication',
            field=models.CharField(max_length=90, verbose_name='Препарат'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='middle_name',
            field=models.CharField(max_length=90, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='privilege_type',
            field=models.CharField(choices=[('Ветеран', 'Ветеран'), ('Чернобыль', 'Чернобыль'), ('Ребёнок-инвалид до 18 лет', 'Ребёнок-инвалид до 18 лет'), ('Инвалид I - II группы', 'Инвалид I - II группы'), ('Инвалид III группы', 'Инвалид III группы')], default=0, max_length=90, verbose_name='Льгота'),
        ),
    ]
