# Generated by Django 3.0.8 on 2020-07-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20200709_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stats',
            options={'verbose_name_plural': 'Статистика'},
        ),
        migrations.AddField(
            model_name='stats',
            name='type_2',
            field=models.IntegerField(default=0, editable=False, verbose_name='Чернобыль'),
        ),
        migrations.AddField(
            model_name='stats',
            name='type_3',
            field=models.IntegerField(default=0, editable=False, verbose_name='Ребёнок-инвалид до 18 лет'),
        ),
        migrations.AddField(
            model_name='stats',
            name='type_4',
            field=models.IntegerField(default=0, editable=False, verbose_name='Инвалид I - II группы'),
        ),
        migrations.AddField(
            model_name='stats',
            name='type_5',
            field=models.IntegerField(default=0, editable=False, verbose_name='Инвалид III группы'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='type_1',
            field=models.IntegerField(default=0, editable=False, verbose_name='Ветеран'),
        ),
    ]
