# Generated by Django 3.0.8 on 2020-08-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20200721_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_recipe',
            field=models.DateField(auto_now_add=True, verbose_name='Дата выдачи рецепта'),
        ),
    ]
