# Generated by Django 3.0.8 on 2020-08-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_auto_20200802_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_recipe',
            field=models.DateField(auto_now_add=True, verbose_name='Дата выдачи рецепта'),
        ),
    ]
